#pragma once

#include <cstdint>
#include "memory.h"
#include "register_file.h"

namespace GameBoy {

constexpr uint8_t FLAG_ZERO_MASK = 1 << 7;
constexpr uint8_t FLAG_SUBTRACT_MASK = 1 << 6; // Also known as the 'N' flag
constexpr uint8_t FLAG_HALF_CARRY_MASK = 1 << 5; // For a carry from bit 3-4 or 11-12
constexpr uint8_t FLAG_CARRY_MASK = 1 << 4;

constexpr uint8_t INSTRUCTION_PREFIX_BYTE = 0xcb;
constexpr uint8_t ENABLE_INTERRUPTS_OPCODE = 0xfb;

class CPU {
public:
    CPU(Memory &memory) : memory{memory} {}
    void print_register_values() const;
    void execute_instruction(uint8_t opcode);

private:
    Memory &memory;
    RegisterFile<std::endian::native> registers;
    uint64_t cycles_elapsed{};
    bool is_stopped{};
    bool is_halted{};
    bool are_interrupts_enabled{};
    bool did_enable_interrupts_execute{};

    using Instruction = void (CPU::*)();
    static const Instruction instruction_table[0x100];
    static const Instruction extended_instruction_table[0x100];

    // Instruction Helpers
    bool is_flag_set(uint8_t flag_mask) const;
    void update_flags(bool new_zero_state, bool new_subtract_state, bool new_half_carry_state, bool new_carry_state);
    
    void load_register8_register8(uint8_t &destination_register8, const uint8_t &source_register8);
    void load_register8_immediate8(uint8_t &destination_register8);
    void load_register8_memory_register16(uint8_t &destination_register8, const uint16_t &source_address_register16);
    void load_memory_register16_register8(const uint16_t &destination_address_register16, const uint8_t &source_register8);
    void load_register16_immediate16(uint16_t &destination_register16);
    void increment_register8(uint8_t &register8);
    void decrement_register8(uint8_t &register8);
    void increment_register16(uint16_t &register16);
    void decrement_register16(uint16_t &register16);
    void add_hl_register16(const uint16_t &register16);
    void add_a_register8(const uint8_t &register8);
    void add_with_carry_a_register8(const uint8_t &register8);
    void subtract_a_register8(const uint8_t &register8);
    void subtract_with_carry_a_register8(const uint8_t &register8);
    void and_a_register8(const uint8_t &register8);
    void xor_a_register8(const uint8_t &register8);
    void or_a_register8(const uint8_t &register8);
    void compare_a_register8(const uint8_t &register8);
    void jump_relative_conditional_signed_immediate8(bool is_condition_met);
    void jump_conditional_immediate16(bool is_condition_met);
    void call_conditional_immediate16(bool is_condition_met);
    void return_conditional(bool is_condition_met);
    void push_stack_register16(const uint16_t &register16);
    void pop_stack_register16(uint16_t &register16);
    void restart_address(uint16_t address);

    void rotate_left_circular_register8(uint8_t &register8);
    void rotate_right_circular_register8(uint8_t &register8);
    void rotate_left_through_carry_register8(uint8_t &register8);
    void rotate_right_through_carry_register8(uint8_t &register8);
    void shift_left_arithmetic_register8(uint8_t &register8);
    void shift_right_arithmetic_register8(uint8_t &register8);
    void swap_nibbles_register8(uint8_t &register8);
    void shift_right_logical_register8(uint8_t &register8);
    void bit_test_position_register8(uint8_t bit_position_to_test, const uint8_t &register8);
    void bit_test_position_memory_hl(uint8_t bit_position_to_test);
    void reset_bit_position_register8(uint8_t bit_position_to_reset, uint8_t &register8);
    void set_bit_position_register8(uint8_t bit_position_to_set, uint8_t &register8);

    // Instructions suffixed with their opcode
    void unused_opcode();
    void no_operation_0x00();
    void load_bc_immediate16_0x01();
    void load_memory_bc_a_0x02();
    void increment_bc_0x03();
    void increment_b_0x04();
    void decrement_b_0x05();
    void load_b_immediate8_0x06();
    void rotate_left_circular_a_0x07();
    void load_memory_immediate16_stack_pointer_0x08();
    void add_hl_bc_0x09();
    void load_a_memory_bc_0x0a();
    void decrement_bc_0x0b();
    void increment_c_0x0c();
    void decrement_c_0x0d();
    void load_c_immediate8_0x0e();
    void rotate_right_circular_a_0x0f();
    void stop_immediate8_0x10();
    void load_de_immediate16_0x11();
    void load_memory_de_a_0x12();
    void increment_de_0x13();
    void increment_d_0x14();
    void decrement_d_0x15();
    void load_d_immediate8_0x16();
    void rotate_left_through_carry_a_0x17();
    void jump_relative_signed_immediate8_0x18();
    void add_hl_de_0x19();
    void load_a_memory_de_0x1a();
    void decrement_de_0x1b();
    void increment_e_0x1c();
    void decrement_e_0x1d();
    void load_e_immediate8_0x1e();
    void rotate_right_through_carry_a_0x1f();
    void jump_relative_not_zero_signed_immediate8_0x20();
    void load_hl_immediate16_0x21();
    void load_memory_hli_a_0x22();
    void increment_hl_0x23();
    void increment_h_0x24();
    void decrement_h_0x25();
    void load_h_immediate8_0x26();
    void decimal_adjust_a_0x27();
    void jump_relative_zero_signed_immediate8_0x28();
    void add_hl_hl_0x29();
    void load_a_memory_hli_0x2a();
    void decrement_hl_0x2b();
    void increment_l_0x2c();
    void decrement_l_0x2d();
    void load_l_immediate8_0x2e();
    void complement_a_0x2f();
    void jump_relative_not_carry_signed_immediate8_0x30();
    void load_stack_pointer_immediate16_0x31();
    void load_memory_hload_a_0x32();
    void increment_stack_pointer_0x33();
    void increment_memory_hl_0x34();
    void decrement_memory_hl_0x35();
    void load_memory_hl_immediate8_0x36();
    void set_carry_flag_0x37();
    void jump_relative_carry_signed_immediate8_0x38();
    void add_hl_stack_pointer_0x39();
    void load_a_memory_hload_0x3a();
    void decrement_stack_pointer_0x3b();
    void increment_a_0x3c();
    void decrement_a_0x3d();
    void load_a_immediate8_0x3e();
    void complement_carry_flag_0x3f();
    void load_b_b_0x40();
    void load_b_c_0x41();
    void load_b_d_0x42();
    void load_b_e_0x43();
    void load_b_h_0x44();
    void load_b_l_0x45();
    void load_b_memory_hl_0x46();
    void load_b_a_0x47();
    void load_c_b_0x48();
    void load_c_c_0x49();
    void load_c_d_0x4a();
    void load_c_e_0x4b();
    void load_c_h_0x4c();
    void load_c_l_0x4d();
    void load_c_memory_hl_0x4e();
    void load_c_a_0x4f();
    void load_d_b_0x50();
    void load_d_c_0x51();
    void load_d_d_0x52();
    void load_d_e_0x53();
    void load_d_h_0x54();
    void load_d_l_0x55();
    void load_d_memory_hl_0x56();
    void load_d_a_0x57();
    void load_e_b_0x58();
    void load_e_c_0x59();
    void load_e_d_0x5a();
    void load_e_e_0x5b();
    void load_e_h_0x5c();
    void load_e_l_0x5d();
    void load_e_memory_hl_0x5e();
    void load_e_a_0x5f();
    void load_h_b_0x60();
    void load_h_c_0x61();
    void load_h_d_0x62();
    void load_h_e_0x63();
    void load_h_h_0x64();
    void load_h_l_0x65();
    void load_h_memory_hl_0x66();
    void load_h_a_0x67();
    void load_l_b_0x68();
    void load_l_c_0x69();
    void load_l_d_0x6a();
    void load_l_e_0x6b();
    void load_l_h_0x6c();
    void load_l_l_0x6d();
    void load_l_memory_hl_0x6e();
    void load_l_a_0x6f();
    void load_memory_hl_b_0x70();
    void load_memory_hl_c_0x71();
    void load_memory_hl_d_0x72();
    void load_memory_hl_e_0x73();
    void load_memory_hl_h_0x74();
    void load_memory_hl_l_0x75();
    void halt_0x76();
    void load_memory_hl_a_0x77();
    void load_a_b_0x78();
    void load_a_c_0x79();
    void load_a_d_0x7a();
    void load_a_e_0x7b();
    void load_a_h_0x7c();
    void load_a_l_0x7d();
    void load_a_memory_hl_0x7e();
    void load_a_a_0x7f();
    void add_a_b_0x80();
    void add_a_c_0x81();
    void add_a_d_0x82();
    void add_a_e_0x83();
    void add_a_h_0x84();
    void add_a_l_0x85();
    void add_a_memory_hl_0x86();
    void add_a_a_0x87();
    void add_with_carry_a_b_0x88();
    void add_with_carry_a_c_0x89();
    void add_with_carry_a_d_0x8a();
    void add_with_carry_a_e_0x8b();
    void add_with_carry_a_h_0x8c();
    void add_with_carry_a_l_0x8d();
    void add_with_carry_a_memory_hl_0x8e();
    void add_with_carry_a_a_0x8f();
    void subtract_a_b_0x90();
    void subtract_a_c_0x91();
    void subtract_a_d_0x92();
    void subtract_a_e_0x93();
    void subtract_a_h_0x94();
    void subtract_a_l_0x95();
    void subtract_a_memory_hl_0x96();
    void subtract_a_a_0x97();
    void subtract_with_carry_a_b_0x98();
    void subtract_with_carry_a_c_0x99();
    void subtract_with_carry_a_d_0x9a();
    void subtract_with_carry_a_e_0x9b();
    void subtract_with_carry_a_h_0x9c();
    void subtract_with_carry_a_l_0x9d();
    void subtract_with_carry_a_memory_hl_0x9e();
    void subtract_with_carry_a_a_0x9f();
    void and_a_b_0xa0();
    void and_a_c_0xa1();
    void and_a_d_0xa2();
    void and_a_e_0xa3();
    void and_a_h_0xa4();
    void and_a_l_0xa5();
    void and_a_memory_hl_0xa6();
    void and_a_a_0xa7();
    void xor_a_b_0xa8();
    void xor_a_c_0xa9();
    void xor_a_d_0xaa();
    void xor_a_e_0xab();
    void xor_a_h_0xac();
    void xor_a_l_0xad();
    void xor_a_memory_hl_0xae();
    void xor_a_a_0xaf();
    void or_a_b_0xb0();
    void or_a_c_0xb1();
    void or_a_d_0xb2();
    void or_a_e_0xb3();
    void or_a_h_0xb4();
    void or_a_l_0xb5();
    void or_a_memory_hl_0xb6();
    void or_a_a_0xb7();
    void compare_a_b_0xb8();
    void compare_a_c_0xb9();
    void compare_a_d_0xba();
    void compare_a_e_0xbb();
    void compare_a_h_0xbc();
    void compare_a_l_0xbd();
    void compare_a_memory_hl_0xbe();
    void compare_a_a_0xbf();
    void return_not_zero_0xc0();
    void pop_stack_bc_0xc1();
    void jump_not_zero_immediate16_0xc2();
    void jump_immediate16_0xc3();
    void call_not_zero_immediate16_0xc4();
    void push_stack_bc_0xc5();
    void add_a_immediate8_0xc6();
    void restart_0x00_0xc7();
    void return_zero_0xc8();
    void return_0xc9();
    void jump_zero_immediate16_0xca();
    // 0xcb is only used to prefix an extended instruction
    void call_zero_immediate16_0xcc();
    void call_immediate16_0xcd();
    void add_with_carry_a_immediate8_0xce();
    void restart_0x08_0xcf();
    void return_not_carry_0xd0();
    void pop_stack_de_0xd1();
    void jump_not_carry_immediate16_0xd2();
    // 0xd3 is an unused opcode
    void call_not_carry_immediate16_0xd4();
    void push_stack_de_0xd5();
    void subtract_a_immediate8_0xd6();
    void restart_0x10_0xd7();
    void return_carry_0xd8();
    void return_from_interrupt_0xd9();
    void jump_carry_immediate16_0xda();
    // 0xdb is an unused opcode
    void call_carry_immediate16_0xdc();
    // 0xdb is an unused opcode
    void subtract_with_carry_a_immediate8_0xde();
    void restart_0x18_0xdf();
    void load_memory_high_ram_signed_immediate8_a_0xe0();
    void pop_stack_hl_0xe1();
    void load_memory_high_ram_c_a_0xe2();
    // 0xe3 is an unused opcode
    // 0xe4 is an unused opcode
    void push_stack_hl_0xe5();
    void and_a_immediate8_0xe6();
    void restart_0x20_0xe7();
    void add_sp_signed_immediate8_0xe8();
    void jump_hl_0xe9();
    void load_memory_immediate16_a_0xea();
    // 0xeb is an unused opcode
    // 0xec is an unused opcode
    // 0xed is an unused opcode
    void xor_a_immediate8_0xee();
    void restart_0x28_0xef();
    void load_a_memory_high_ram_immediate8_0xf0();
    void pop_stack_af_0xf1();
    void load_a_memory_high_ram_c_0xf2();
    void disable_interrupts_0xf3();
    // 0xf4 is an unused opcode
    void push_stack_af_0xf5();
    void or_a_immediate8_0xf6();
    void restart_0x30_0xf7();
    void load_hl_stack_pointer_with_signed_offset_0xf8();
    void load_stack_pointer_hl_0xf9();
    void load_a_memory_immediate16_0xfa();
    void enable_interrupts_0xfb();
    // 0xfc is an unused opcode
    // 0xfd is an unused opcode
    void compare_a_immediate8_0xfe();
    void restart_0x38_0xff();

    // Extended Instructions suffixed with their opcode
    void rotate_left_circular_b_0xcb00();
    void rotate_left_circular_c_0xcb01();
    void rotate_left_circular_d_0xcb02();
    void rotate_left_circular_e_0xcb03();
    void rotate_left_circular_h_0xcb04();
    void rotate_left_circular_l_0xcb05();
    void rotate_left_circular_memory_hl_0xcb06();
    void rotate_left_circular_a_0xcb07();
    void rotate_right_circular_b_0xcb08();
    void rotate_right_circular_c_0xcb09();
    void rotate_right_circular_d_0xcb0a();
    void rotate_right_circular_e_0xcb0b();
    void rotate_right_circular_h_0xcb0c();
    void rotate_right_circular_l_0xcb0d();
    void rotate_right_circular_memory_hl_0xcb0e();
    void rotate_right_circular_a_0xcb0f();
    void rotate_left_through_carry_b_0xcb10();
    void rotate_left_through_carry_c_0xcb11();
    void rotate_left_through_carry_d_0xcb12();
    void rotate_left_through_carry_e_0xcb13();
    void rotate_left_through_carry_h_0xcb14();
    void rotate_left_through_carry_l_0xcb15();
    void rotate_left_through_carry_memory_hl_0xcb16();
    void rotate_left_through_carry_a_0xcb17();
    void rotate_right_through_carry_b_0xcb18();
    void rotate_right_through_carry_c_0xcb19();
    void rotate_right_through_carry_d_0xcb1a();
    void rotate_right_through_carry_e_0xcb1b();
    void rotate_right_through_carry_h_0xcb1c();
    void rotate_right_through_carry_l_0xcb1d();
    void rotate_right_through_carry_memory_hl_0xcb1e();
    void rotate_right_through_carry_a_0xcb1f();
    void shift_left_arithmetic_b_0xcb20();
    void shift_left_arithmetic_c_0xcb21();
    void shift_left_arithmetic_d_0xcb22();
    void shift_left_arithmetic_e_0xcb23();
    void shift_left_arithmetic_h_0xcb24();
    void shift_left_arithmetic_l_0xcb25();
    void shift_left_arithmetic_memory_hl_0xcb26();
    void shift_left_arithmetic_a_0xcb27();
    void shift_right_arithmetic_b_0xcb28();
    void shift_right_arithmetic_c_0xcb29();
    void shift_right_arithmetic_d_0xcb2a();
    void shift_right_arithmetic_e_0xcb2b();
    void shift_right_arithmetic_h_0xcb2c();
    void shift_right_arithmetic_l_0xcb2d();
    void shift_right_arithmetic_memory_hl_0xcb2e();
    void shift_right_arithmetic_a_0xcb2f();
    void swap_nibbles_b_0xcb30();
    void swap_nibbles_c_0xcb31();
    void swap_nibbles_d_0xcb32();
    void swap_nibbles_e_0xcb33();
    void swap_nibbles_h_0xcb34();
    void swap_nibbles_l_0xcb35();
    void swap_nibbles_memory_hl_0xcb36();
    void swap_nibbles_a_0xcb37();
    void shift_right_logical_b_0xcb38();
    void shift_right_logical_c_0xcb39();
    void shift_right_logical_d_0xcb3a();
    void shift_right_logical_e_0xcb3b() ;
    void shift_right_logical_h_0xcb3c();
    void shift_right_logical_l_0xcb3d();
    void shift_right_logical_memory_hl_0xcb3e();
    void shift_right_logical_a_0xcb3f();
    void bit_test_0_b_0xcb40();
    void bit_test_0_c_0xcb41();
    void bit_test_0_d_0xcb42();
    void bit_test_0_e_0xcb43();
    void bit_test_0_h_0xcb44();
    void bit_test_0_l_0xcb45();
    void bit_test_0_memory_hl_0xcb46();
    void bit_test_0_a_0xcb47();
    void bit_test_1_b_0xcb48();
    void bit_test_1_c_0xcb49();
    void bit_test_1_d_0xcb4a();
    void bit_test_1_e_0xcb4b();
    void bit_test_1_h_0xcb4c();
    void bit_test_1_l_0xcb4d();
    void bit_test_1_memory_hl_0xcb4e();
    void bit_test_1_a_0xcb4f();
    void bit_test_2_b_0xcb50();
    void bit_test_2_c_0xcb51();
    void bit_test_2_d_0xcb52();
    void bit_test_2_e_0xcb53();
    void bit_test_2_h_0xcb54();
    void bit_test_2_l_0xcb55();
    void bit_test_2_memory_hl_0xcb56();
    void bit_test_2_a_0xcb57();
    void bit_test_3_b_0xcb58();
    void bit_test_3_c_0xcb59();
    void bit_test_3_d_0xcb5a();
    void bit_test_3_e_0xcb5b();
    void bit_test_3_h_0xcb5c();
    void bit_test_3_l_0xcb5d();
    void bit_test_3_memory_hl_0xcb5e();
    void bit_test_3_a_0xcb5f();
    void bit_test_4_b_0xcb60();
    void bit_test_4_c_0xcb61();
    void bit_test_4_d_0xcb62();
    void bit_test_4_e_0xcb63();
    void bit_test_4_h_0xcb64();
    void bit_test_4_l_0xcb65();
    void bit_test_4_memory_hl_0xcb66();
    void bit_test_4_a_0xcb67();
    void bit_test_5_b_0xcb68();
    void bit_test_5_c_0xcb69();
    void bit_test_5_d_0xcb6a();
    void bit_test_5_e_0xcb6b();
    void bit_test_5_h_0xcb6c();
    void bit_test_5_l_0xcb6d();
    void bit_test_5_memory_hl_0xcb6e();
    void bit_test_5_a_0xcb6f();
    void bit_test_6_b_0xcb70();
    void bit_test_6_c_0xcb71();
    void bit_test_6_d_0xcb72();
    void bit_test_6_e_0xcb73();
    void bit_test_6_h_0xcb74();
    void bit_test_6_l_0xcb75();
    void bit_test_6_memory_hl_0xcb76();
    void bit_test_6_a_0xcb77();
    void bit_test_7_b_0xcb78();
    void bit_test_7_c_0xcb79();
    void bit_test_7_d_0xcb7a();
    void bit_test_7_e_0xcb7b();
    void bit_test_7_h_0xcb7c();
    void bit_test_7_l_0xcb7d();
    void bit_test_7_memory_hl_0xcb7e();
    void bit_test_7_a_0xcb7f();
};

} // namespace GameBoy
